# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/Cpp-Repo-Template/Cpp-Repo-Template

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/Cpp-Repo-Template/Cpp-Repo-Template

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/Cpp-Repo-Template/Cpp-Repo-Template/CMakeFiles /home/runner/work/Cpp-Repo-Template/Cpp-Repo-Template//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/Cpp-Repo-Template/Cpp-Repo-Template/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named executable

# Build rule for target.
executable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 executable
.PHONY : executable

# fast build rule for target.
executable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/build
.PHONY : executable/fast

#=============================================================================
# Target rules for targets named tests_executable

# Build rule for target.
tests_executable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests_executable
.PHONY : tests_executable

# fast build rule for target.
tests_executable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/build
.PHONY : tests_executable/fast

#=============================================================================
# Target rules for targets named doc_doxygen

# Build rule for target.
doc_doxygen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc_doxygen
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc_doxygen.dir/build.make CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.s
.PHONY : main.cpp.s

src/Sample.o: src/Sample.cpp.o
.PHONY : src/Sample.o

# target to build an object file
src/Sample.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Sample.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/src/Sample.cpp.o
.PHONY : src/Sample.cpp.o

src/Sample.i: src/Sample.cpp.i
.PHONY : src/Sample.i

# target to preprocess a source file
src/Sample.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Sample.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/src/Sample.cpp.i
.PHONY : src/Sample.cpp.i

src/Sample.s: src/Sample.cpp.s
.PHONY : src/Sample.s

# target to generate assembly for a file
src/Sample.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/src/Sample.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/src/Sample.cpp.s
.PHONY : src/Sample.cpp.s

test/Other/OtherTest.o: test/Other/OtherTest.cpp.o
.PHONY : test/Other/OtherTest.o

# target to build an object file
test/Other/OtherTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/Other/OtherTest.cpp.o
.PHONY : test/Other/OtherTest.cpp.o

test/Other/OtherTest.i: test/Other/OtherTest.cpp.i
.PHONY : test/Other/OtherTest.i

# target to preprocess a source file
test/Other/OtherTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/Other/OtherTest.cpp.i
.PHONY : test/Other/OtherTest.cpp.i

test/Other/OtherTest.s: test/Other/OtherTest.cpp.s
.PHONY : test/Other/OtherTest.s

# target to generate assembly for a file
test/Other/OtherTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/Other/OtherTest.cpp.s
.PHONY : test/Other/OtherTest.cpp.s

test/Sample/SampleTest.o: test/Sample/SampleTest.cpp.o
.PHONY : test/Sample/SampleTest.o

# target to build an object file
test/Sample/SampleTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/Sample/SampleTest.cpp.o
.PHONY : test/Sample/SampleTest.cpp.o

test/Sample/SampleTest.i: test/Sample/SampleTest.cpp.i
.PHONY : test/Sample/SampleTest.i

# target to preprocess a source file
test/Sample/SampleTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/Sample/SampleTest.cpp.i
.PHONY : test/Sample/SampleTest.cpp.i

test/Sample/SampleTest.s: test/Sample/SampleTest.cpp.s
.PHONY : test/Sample/SampleTest.s

# target to generate assembly for a file
test/Sample/SampleTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/Sample/SampleTest.cpp.s
.PHONY : test/Sample/SampleTest.cpp.s

test/mainTest.o: test/mainTest.cpp.o
.PHONY : test/mainTest.o

# target to build an object file
test/mainTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/mainTest.cpp.o
.PHONY : test/mainTest.cpp.o

test/mainTest.i: test/mainTest.cpp.i
.PHONY : test/mainTest.i

# target to preprocess a source file
test/mainTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/mainTest.cpp.i
.PHONY : test/mainTest.cpp.i

test/mainTest.s: test/mainTest.cpp.s
.PHONY : test/mainTest.s

# target to generate assembly for a file
test/mainTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_executable.dir/build.make CMakeFiles/tests_executable.dir/test/mainTest.cpp.s
.PHONY : test/mainTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc_doxygen"
	@echo "... executable"
	@echo "... tests_executable"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Sample.o"
	@echo "... src/Sample.i"
	@echo "... src/Sample.s"
	@echo "... test/Other/OtherTest.o"
	@echo "... test/Other/OtherTest.i"
	@echo "... test/Other/OtherTest.s"
	@echo "... test/Sample/SampleTest.o"
	@echo "... test/Sample/SampleTest.i"
	@echo "... test/Sample/SampleTest.s"
	@echo "... test/mainTest.o"
	@echo "... test/mainTest.i"
	@echo "... test/mainTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

