name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    name: Build 
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v3.0.4
      env:
        cache-name: cache-dependencies
      with:
        # folder where apt-get cache packages
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - if: ${{ steps.cache-dependencies.outputs.cache-hit == 'false' }}
      name: Cache non found
      continue-on-error: true
      run: echo "Cache not found"
      
    - name: install doxygen and ccache
      run: sudo apt install -y doxygen ccache
    
    - name: Create build folder
      # Create build folder if not exist
      run: mkdir -p build
      
    - name: cd build
      run: cd build
      
    - name: CMake
      # Run cmake
      run: cmake ${{github.workspace}}
      
    - name: make
      run: make
      
  Test:
    runs-on: ubuntu-latest
    name: Test 
    steps:
      - name: Tests
        run: ./tests_executable -s
