name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: mkdir build
      run: mkdir -p build
      
    - name: ls
      run: ls -a
      
    - name: cd build
      run: cd build
      
    - name: CMake
      run: cmake ${{github.workspace}}
      
    - name: make
      run: make
    
    - name: Run test
      run: ./tests_executable
      
